### ISSUE TITLE
Prediction scores of drug–protein interactions

### ISSUE THREAD

**Issue by ghost** [luoyunan/DTINet#10]
Dear Yunan,

I was wondering what is the output of the DTINet. Is it only AUROC and AUPR?
Can we have Prediction scores of drug–protein interactions (XZY<sup>T</sup>) as an output? Is it the mean Z-score following train_mf ?

Thanks a lot!

**Comment by luoyunan** [comment]
Yes. You can use the prediction score like this
https://github.com/luoyunan/DTINet/blob/master/src/DTINet.m#L33

Note that although the variable is named as "Zscore", it is not the mean-centered average divided by the standard deviation. It's just a scalar score -- a higher score suggests it's more likely to be a DTI.

**Comment by ghost** [comment]
Thanks for your response.
does the sign (+/-) show anything?

**Comment by luoyunan** [comment]
Sorry for the late response. 

The sign does not have a particular meaning by definition.
