### ISSUE TITLE
How can I get __train_mf.py

### ISSUE THREAD

**Issue by Carboxy** [luoyunan/DTINet#11]
Hello，Professor luo. The third line of  \DTINet-master\src\leml-imf\src\python\train_mf.py, which writes "import __train_mf as c_train_mf". How can I get _train_mf.py.

**Comment by luoyunan** [comment]
Hi,

Please first install the IMC package:
```
> git clone https://github.com/luoyunan/DTINet.git
> cd DTINet/src
> bash install_imc.sh
```
Then you can follow the tutorial to run "run_DTINet.m" in MATLAB.

**Comment by Carboxy** [comment]
Thanks a lot!

**Comment by Carboxy** [comment]
Hello，Professor luo. I'm afraid I'm going to bother you again. I'm trying to build DTINet on python, but I am confronted with some difficulies in call train_mf.py. So how can I use IMC package in Python.

**Comment by luoyunan** [comment]
There should be a README or example file in the `leml-imf-src.zip` package showing how to use it in Python.
