### ISSUE TITLE
Something went wrong on my mac when install IMC

### ISSUE THREAD

**Issue by kun931213** [luoyunan/DTINet#2]
Hi~
I'm a Ph.D. candidate and going to follow ur algorithm.
I found everything went well except installing the IMC module.
When I run the IMC install script (download_imc.sh) on my Mac in terminal.app, warnings will happen:

> mkdir -p matlab; cd src/matlab; matlab -nodisplay -nosplash -nojvm -r "make; exit"; cp *mex* ../../matlab/
> /bin/sh: matlab: command not found
> cp: *mex*: No such file or directory
> make: *** [matlab] Error 1

Finally, I found there may be something wrong with the code in your script(download_imc.sh) : make matlab.

This code does not work well on mac (osx system).

I do not know how to resolve this problem. Could you please help me? 

Thank u a lot!

**Comment by luoyunan** [comment]
Hi @kun931213 ,

This is not an issue of DTINet. It seems the error occurred when you installed the [IMC](http://bigdata.ices.utexas.edu/software/inductive-matrix-completion/) dependency (called by `download_ims.sh`). 

As it showed `/bin/sh: matlab: command not found`, I guess the reason you had the error is that you don't have MATLAB installed on your Mac, or the directory of MATLAB hasn't been set properly in the PATH environment variable.

Hope this is helpful!

**Comment by kun931213** [comment]
Hi~ i checked again to confirm that i do have matlab. However, sadly, it went wrong on my mac agian and again. The "make matlab" code just can't work! 

What do u mean the directory of MATLAB hasn't been set properly in the PATH environment variable? i use the [terminal] to execute all the command lines, i did not choose Path environment at all and i do not know how to choose the Path environment.

Thank u for ur reply!

**Comment by kun931213** [comment]
Are u still in THU? U know, Im a Phd candidate in THU (School of basic medical sciences). We may meet and take a few minutes to solve the problem. That will be really nice and helpful of u! Thank u again~! My wechat number is : kun931213, please add me if u want.
