### ISSUE TITLE
about IMC:download_imc.sh has expired.

### ISSUE THREAD

**Issue by ChoungJX** [luoyunan/DTINet#4]
### Could you please provide a new url?

**Comment by luoyunan** [comment]
Hi @ChoungJX ,

The URL of IMC has been expired and I'm not sure whether the author of IMC will provide a working URL for downloading IMC in the future. 

For now, I added a local version of IMC into the `/src` directory. Please try to use the `install_imc.sh` to install IMC again. Feel free to let me know any issues you encountered.

**Comment by ChoungJX** [comment]
Thank you very much!
