### ISSUE TITLE
program running error

### ISSUE THREAD

**Issue by jerrywu65** [luoyunan/DTINet#5]
when I run the run_DTINet.m , there's a problem following like that:
Invalid MEX-file '/home/ruancy/wrj/DTINet/src/train_mf.mexa64':
/usr/local/MATLAB/R2014a/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6:
version `CXXABI_1.3.8' not found (required by
/home/ruancy/wrj/DTINet/src/train_mf.mexa64)

Error in DTINet (line 31)
		[W, H, ~] = train_mf(Xtrain, sparse(drug_feat),
                sparse(prot_feat), ...

how can I solve it,thx!

**Comment by luoyunan** [comment]
Hi @jerrywu65 
Seems this is an issue of your environment setting but not a bug of DTINet. It looks like some library is missing or the version is too old. Could you google "version `CXXABI_1.3.8' not found" and try various solutions people have suggested? Or try DTINet on another machine?
