### ISSUE TITLE
I 'm confused about the difference between two data files.

### ISSUE THREAD

**Issue by yangxinhaosmu** [luoyunan/DTINet#6]
My question may be a little stupid.....
What's the difference between Similarity_Matrix_Drugs.txt and Sim_mat_drug_drug.txt which is generated by compute_similarity.m in matlab?
Can Sim_mat_drug_drug.txt presents the structural similarities of drugs based on drug compounds’ chemical structures?
What does the Drug similarity scores mean?
If the information is confidential，please forgive my rudeness.
Thanks a lot!

**Comment by luoyunan** [comment]
Hi @yangxinhaosmu 
Similarity_Matrix_Drugs.txt is the structure similarity (Tonimoto scores of chemical structures). Sim_mat_drug_drug.txt is the pairwise similarity (Jaccard similarity) based on drug-drug interaction profile.

**Comment by yangxinhaosmu** [comment]
Thank you so much!
