### ISSUE TITLE
how to run this project

### ISSUE THREAD

**Issue by jenny1022** [luoyunan/DTINet#7]
Hi, I want to run this project now, and I'll follow your instructions in Tutorial. But I have the following questions to ask you.
1.I  want to know what  **interaction/association matrices** is in the first step in Tutorial.
2.I wonder if it is necessary to install this imc? I have downloaded your project, I find its compressed package in src directory. Does that mean I don't need to install it anymore? And how can I use this imc if I want to run the DTINet.
3.Will I be able to run successfully after these steps?

Please help me, I  really spent a lot of time on this project. Thanks a lot!

**Comment by luoyunan** [comment]
Hi @jenny1022 

Sorry for the late response.

1. Interaction/association matrices are drug-related and protein-related matrices, e.g., protein-protein interaction matrix, drug-disease association matrix, protein-disease association matrix, etc. You can find all the necessary data in the `data/` folder.

2. Yes. The IMC library is needed. You can run `bash install_imc.sh` in the `src/` directory to install the IMC library.

3. You should be able to run DTINet following the steps described in the Tutorial. Feel free to ask if you have any questions.

**Comment by xtzhang-AI4S** [comment]
How to get Interaction/association matrices for external data?
